services:
  notifications-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_notifications
    ports:
      - '5439:5432'
    volumes:
      - notifications-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_notifications']
      interval: 5s
      timeout: 3s
      retries: 5

  notifications-postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_notifications_test
    ports:
      - '5440:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_notifications_test']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  notifications-pgdata:
