services:
  payments-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_payments
    ports:
      - '5437:5432'
    volumes:
      - payments-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_payments']
      interval: 5s
      timeout: 3s
      retries: 5

  payments-postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_payments_test
    ports:
      - '5438:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_payments_test']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  payments-pgdata:
