services:
  trips-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_trips
    ports:
      - '5435:5432'
    volumes:
      - trips-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_trips']
      interval: 5s
      timeout: 3s
      retries: 5

  trips-postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sapar
      POSTGRES_PASSWORD: sapar_secret
      POSTGRES_DB: sapar_trips_test
    ports:
      - '5436:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'sapar', '-d', 'sapar_trips_test']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  trips-pgdata:
