name: Deploy to PROD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: false
        default: "prod"
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - name: Deploy locally on PROD server
        run: |
          cd /opt/sapar
          export IMAGE_TAG="${{ inputs.image_tag }}"
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ozy-max --password-stdin
          docker compose pull
          docker compose up -d
          docker image prune -f
